# -*- coding: utf-8 -*-
"""OATutor Quick Deploy + Content Notebook

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11X3eW9cDnRcvROaCWglPM5VH0NRAXFKp

# OATutor Custom Content Quick Deploy
[codebase](https://github.com/CAHLR/OATutor) - [paper](https://doi.org/10.1145/3544548.3581574)

This notebook walks through the necessary terminal commands to process content and deploy OATutor. These commands are run on colab's underlying VM but can be run on any system supporting npm. Alternatively, the platform can be forked and deployed using git-pages (e.g., [https://cahlr.github.io/OATutor](https://cahlr.github.io/OATutor)).

NOTE: A limitation of this colab approach is that the frontend will only run while this notebook session is active.

## Install nodeJS
"""

!sudo apt install curl
!curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

"""## Clone the git repo"""

!git clone https://github.com/CAHLR/OATutor.git
!git clone https://github.com/CAHLR/OATutor-Tooling.git
!git clone https://github.com/CAHLR/Content-Files.git

"""## Process Content

### Install required libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/OATutor-Tooling/content_script
!pip install --upgrade pip --no-cache-dir
!pip install -r requirements.txt

"""### Run content script"""

# Commented out IPython magic to ensure Python compatibility.
# %mkdir /content/OATutor/src/content-sources/oatutor/Content
# %cd /content/OATutor/src/content-sources/oatutor/Content
# This converts content from all one sheet
!python3 /content/OATutor-Tooling/content_script/final.py local "/content/Content-Files/Problem Bank URL.xlsx"

"""After the command runs, you should see the JSON content file structure under OATutor/src/content-sources/oatutor/OpenStax Content/, as well as `coursePlans.json`, `bktParams.json`, and `skillModel.json` under OATutor/src/content-sources/oatutor/. Note: again, you might need to refresh the directory.

### Deploy Locally
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/OATutor/src/content-sources/oatutor
# %mv "OpenStax Content" "content-pool"
# %mkdir bkt-params
# %mv bktParams.json bkt-params/defaultBKTParams.json
# %cp bkt-params/defaultBKTParams.json bkt-params/experimentalBKTParams.json
# %cd /content/OATutor/src/tools
!node preprocessProblemPool.js
# %cd /content/OATutor

"""## Install OATutor node dependencies"""

!npm install

"""## Deploy"""

# This command runs the frontend server in the background
!while true; do npm run start >frontend-log.txt 2>&1; sleep 5; done >/dev/null 2>&1 &

"""#### The below cell will contain debug logs of the frontend, re-run the cell to fetch the latest logs"""

!cat frontend-log.txt

"""## Set up localtunnel to access Colab web server"""

!npm install -g localtunnel

# This command runs the local tunnel port forwarding in the background
!while true; do nohup lt --port 3001 >url.txt 2>&1; sleep 5; done >/dev/null 2>&1 &

"""#### Get URL to frontend. Re-run to view latest logs from runtime."""

!cat url.txt

"""#### Get the IP address of the Colab VM that the below URL will ask for"""

!curl ipv4.icanhazip.com